# Generated by Django 4.2.7 on 2025-12-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('hostel', 'Hostel'), ('apartment', 'Apartment'), ('hotel', 'Hotel'), ('rental', 'Rental')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['owner', 'type'], name='properties__owner_i_be9dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['name'], name='properties__name_47b1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='properties__created_72ecc3_idx'),
        ),
    ]
